version: '2'
services:
  zookeeper:
    image: enow/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - SERVER_ID=1
      - ADDITIONAL_ZOOKEEPER_1=server.1=0.0.0.0:2888:3888
  nimbus:
    image: enow/storm
    command: nimbus -c storm.local.hostname=\"nimbus\" -c nimbus.seeds=\"[\\\"192.168.99.100\\\"]\"
    container_name: nimbus
    environment:
      - STORM_ZOOKEEPER_SERVERS=192.168.99.100
    ports:
      - "3773:3773"
      - "3772:3772"
      - "6627:6627"
    depends_on:
      - zookeeper
  supervisor:
    image: enow/storm
    command: supervisor -c storm.local.hostname=\"nimbus\" -c nimbus.seeds=\"[\\\"192.168.99.100\\\"]\" -c supervisor.slots.ports=\"[6700,6701,6702,6703]\"
    container_name: supervisor
    environment:
      - STORM_ZOOKEEPER_SERVERS=192.168.99.100
      - initial_delay_seconds=20
    ports:
      - "8000:8000"
    depends_on:
      - nimbus
  ui:
    image: enow/storm
    command: ui -c storm.local.hostname=\"nimbus\" -c nimbus.seeds=\"[\\\"192.168.99.100\\\"]\"
    container_name: ui
    environment:
      - STORM_ZOOKEEPER_SERVERS=192.168.99.100
    ports:
      - "8080:8080"
    depends_on:
      - nimbus
  kafka:
    image: enow/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "proceed:3:1,event:3:1,feed:3:1,trigger:3:1,order:3:1,log:3:1"
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  topology:
    build: .
    container_name: topology
    command: jar ./topology.jar com.enow.storm.main.main Action Trigger -c storm.local.hostname=\"nimbus\" -c nimbus.seeds=\"[\\\"192.168.99.100\\\"]\"
    environment:
      - STORM_ZOOKEEPER_SERVERS=192.168.99.100
      - initial_delay_seconds=100
    depends_on:
      - nimbus
networks:
  default:
    external:
      name: storm
